// This file is auto-generated by extract_book_chapters.py

export const bookChapters2022_23 = [
    {
        "title": "Chandra, B.R., Kumar, Swarm Optimizer (RSO): A Novel Swarm Intelligence-Based Optimization Algorithm for Tackling Difficult Optimization Problems",
        "authors": "",
        "year_published": "2023",
        "publisher": "Lecture Notes in Networks and Systems, 648 LNNS, pp. 549-561.LinkDOI: 10.1007/978-3-031-27524-1_52",
        "link": "https://www.scopus.com/inward/record.uri?eid=2-s2.0-85152576837&doi=10.1007%2f978-3-031-27524-1_52&partnerID=40&md5=4d77cc8b50b6d676c38d364d4ff69e86"
    },
    {
        "title": "Reddy, G.P.R., Kumar, D.M., Rajesh, K., Sagar, Y.C., Rao, J.N., Performance Analysis of Diode Clamped and Flying Capacitor Multilevel Matrix Converter Used for Terms and conditions Privacy policy",
        "authors": "",
        "year_published": "2023",
        "publisher": ", Lecture Notes in Electrical Engineering, 957, pp. 59-73.LinkDOI: 10.1007/978-981-19-6913-3_4",
        "link": "https://www.scopus.com/inward/record.uri?eid=2-s2.0-85151066266&doi=10.1007%2f978-981-19-6913-3_4&partnerID=40&md5=f04e14f48d11e50946c3a4eb2506a1ee"
    },
    {
        "title": "Munassar, N.M.A., Gunjan, V.K., Kumar, M.R., WA-SCV Analysis for Scope Creep Management in a Software Project Requirements",
        "authors": "",
        "year_published": "2022",
        "publisher": "Lecture Notes in Electrical Engineering, 828, pp. 1251-1262.LinkDOI: 10.1007/978-981-16-7985-8_130",
        "link": "https://www.scopus.com/inward/record.uri?eid=2-s2.0-85130964190&doi=10.1007%2f978-981-16-7985-8_130&partnerID=40&md5=26c79340d5e863afcaa16b03217feab5"
    },
    {
        "title": "Rudra Kumar, M., Gunjan, V.K., Machine Learning Based Solutions for Human Resource Systems Management",
        "authors": "",
        "year_published": "2022",
        "publisher": "Lecture Notes in Electrical Engineering, 828, pp. 1239-1249. Cited 2 times.LinkDOI: 10.1007/978-981-16-7985-8_129",
        "link": "https://www.scopus.com/inward/record.uri?eid=2-s2.0-85130934713&doi=10.1007%2f978-981-16-7985-8_129&partnerID=40&md5=ed1ba474adf2f8c4dd25db5e953ca54c"
    },
    {
        "title": "Rudra Kumar, M., Gunjan, V.K., Peer Level Credit Rating: An Extended Plugin for Credit Scoring Framework",
        "authors": "",
        "year_published": "2022",
        "publisher": "Lecture Notes in Electrical Engineering, 828, pp. 1227-1237LinkDOI: 10.1007/978-981-16-7985-8_128",
        "link": "https://www.scopus.com/inward/record.uri?eid=2-s2.0-85130898214&doi=10.1007%2f978-981-16-7985-8_128&partnerID=40&md5=19305d0cf6d256ff049164d526a8d68b"
    },
    {
        "title": "Aditya Sai Srinivas, T., Ramasubbareddy, S., Govinda, K., Loan Default Prediction Using Machine Learning Techniques",
        "authors": "",
        "year_published": "2022",
        "publisher": "Lecture Notes in Networks and Systems, 385, pp. 529-535. Cited 1 time.LinkDOI: 10.1007/978-981-16-8987-1_56",
        "link": "https://www.scopus.com/inward/record.uri?eid=2-s2.0-85127702248&doi=10.1007%2f978-981-16-8987-1_56&partnerID=40&md5=b661557e8f784818125d45652e906cca"
    },
    {
        "title": "Varaprasad, R., Ramasubbareddy, S., Govinda, K., Event Recommendation System Using Machine Learning Techniques",
        "authors": "",
        "year_published": "2022",
        "publisher": "Lecture Notes in Networks and Systems, 385, pp. 627-634.LinkDOI: 10.1007/978-981-16-8987-1_67",
        "link": "https://www.scopus.com/inward/record.uri?eid=2-s2.0-85127686793&doi=10.1007%2f978-981-16-8987-1_67&partnerID=40&md5=f67d3d72c1ec48ec140c0c632841b705"
    },
    {
        "title": "Rudra Kumar, M., Pathak, R., Gunjan, V.K., Diagnosis and Medicine Prediction for COVID-19 Using Machine Learning Approach",
        "authors": "",
        "year_published": "2022",
        "publisher": "Lecture Notes in Electrical Engineering, 834, pp. 123-133. Cited 8 times.LinkDOI: 10.1007/978-981-16-8484-5_10",
        "link": "https://www.scopus.com/inward/record.uri?eid=2-s2.0-85126357543&doi=10.1007%2f978-981-16-8484-5_10&partnerID=40&md5=361f95b6677e55860f156410f88911bd"
    },
    {
        "title": "Rudra Kumar, M., Pathak, R., Gunjan, V.K., Machine Learning-Based Project Resource Allocation Fitment Analysis System (ML-PRAFS)",
        "authors": "",
        "year_published": "2022",
        "publisher": "Lecture Notes in Electrical Engineering, 834, pp. 1-14.LinkDOI: 10.1007/978-981-16-8484-5_1",
        "link": "https://www.scopus.com/inward/record.uri?eid=2-s2.0-85126352588&doi=10.1007%2f978-981-16-8484-5_1&partnerID=40&md5=35a90feccb592e9ec01dbd0ea1bfca4d"
    },
    {
        "title": "Reddy, G.P.R. Kumar, D.M. Rajesh, K. Sagar, Y.C. Rao, J.N., Performance Analysis of Diode Clamped and Flying Capacitor Multilevel Matrix Converter Used for DFIG-Based Wind System, March 2023, Part of the Lecture Notes in Electrical Engineering book series (LNEE, volume 957",
        "authors": "",
        "year_published": "",
        "publisher": "",
        "link": ""
    }
];

export const bookChapters2021_22 = [
    {
        "title": "Tirupal T., et al., \u201cMultimodal Medical Image Fusion Based on Interval-Valued Intuitionistic Fuzzy Sets\u201d, In: Kumar R., Chauhan V.S., Talha M., Pathak H. (eds) Machines, Mechanism and Robotics. Lecture Notes in Mechanical Engineering. Springer, Singapore. ISBN 978-981-16-0549-9, pp. 965-971, 22 July 2021.Link",
        "authors": "",
        "year_published": "",
        "publisher": "",
        "link": "https://doi.org/10.1007/978-981-16-0550-5_91"
    },
    {
        "title": "Tirupal T., et al., \u201cThe Influence of Ultrasound for the Protection of Animals on Highways Through Electronic Circuits\u201d, In: Kumar R., Chauhan V.S., Talha M., Pathak H. (eds) Machines, Mechanism and Robotics. Lecture Notes in Mechanical Engineering. Springer, Singapore. ISBN 978-981-16-0549-9, pp. 965-971, 22 July 2021.Link",
        "authors": "",
        "year_published": "",
        "publisher": "",
        "link": "https://doi.org/10.1007/978-981-16-0550-5_92"
    },
    {
        "title": "Tirupal T., et al., \u201cAutomatic Seed Cum Fertilizer Sowing Machine with Water Dripping on Seeds\u201d, In: Kumar R., Chauhan V.S., Talha M., Pathak H. (eds) Machines, Mechanism and Robotics. Lecture Notes in Mechanical Engineering. Springer, Singapore. ISBN 978-981-16-0549-9, pp. 965-971, 22 July 2021.Link",
        "authors": "",
        "year_published": "",
        "publisher": "",
        "link": "https://doi.org/10.1007/978-981-16-0550-5_97"
    },
    {
        "title": "Aditya Sai Srinivas, T., Somula, R., Aravind, K., Manivannan, S.S., Pattern prediction using binary trees",
        "authors": "",
        "year_published": "2021",
        "publisher": ", Lecture Notes in Networks and Systems, 171, pp. 43-52.LinkDOI: 10.1007/978-981-33-4543-0_6",
        "link": "https://www.scopus.com/inward/record.uri?eid=2-s2.0-85105064284&doi=10.1007%2f978-981-33-4543-0_6&partnerID=40&md5=27862669f407229799b099475484e9a7"
    }
];

export const bookChapters2020_21 = [
    {
        "title": "V.Vijaya Kishore et al., \u201cBecoming a Change Maker by Reinventing Education During Epidemic, Pandemic and Outbreak-Covid-19\u201d, Presented in Text Book Titled \u201cInnovative teaching and Learning process during COVID-19\u201d ISBN: 978-93-89631-64-7, pp.42-45, 14 November 2020, Google Scholar, IOR International Press.Link",
        "authors": "",
        "year_published": "",
        "publisher": "",
        "link": "https://books.iorpress.org/index.php/ior/catalog/book/29"
    },
    {
        "title": "P.Bindu Swetha et al., \u201cInnovative Teaching & Learning Process Future Education Industry\u201d, Presented in Text Book Titled \u201cInnovative teaching and Learning process during COVID-19\u201d ISBN: 978-93-89631-64-7, pp.39-41, 14 November 2020, Google Scholar, IOR International Press.Link",
        "authors": "",
        "year_published": "",
        "publisher": "",
        "link": "https://books.iorpress.org/index.php/ior/catalog/book/29"
    },
    {
        "title": "Vinay Babu, S ,Raghu Babu, U., Venkata Ramana, N.,., Pavithra, P. \u201cEffect of Pond Ash on Black Stone Waste Aggregate Concrete\u201d",
        "authors": "",
        "year_published": "2020",
        "publisher": "Lecture Notes in Civil Engineering, 61, pp. 345-353.Link",
        "link": "https://link.springer.com/chapter/10.1007%2F978-3-030-24314-2_28#citeas"
    },
    {
        "title": "Srinivas Rao, C., Amrutha, P., Kumar, M.V. \u201cA novel method for dynamic stability enhancement of smib system\u201d",
        "authors": "",
        "year_published": "2020",
        "publisher": "Lecture Notes in Electrical Engineering, 569, pp. 357-367.LinkDOI: 10.1007/978-981-13-8942-9_30",
        "link": "https://www.scopus.com/inward/record.uri?eid=2-s2.0-85073337009&doi=10.1007%2f978-981-13-8942-9_30&partnerID=40&md5=1d6b317c485a153ef335048b997d4c90"
    },
    {
        "title": "Pandu Ranga Reddy, G., Chandra Sekhar, J.N., Naresh, B., Kumar, M.V. \u201cComparative analysis of flying capacitor and h-bridge multilevel matrix converters for dfig based wind energy conversion system\u201d",
        "authors": "",
        "year_published": "2020",
        "publisher": "Lecture Notes in Electrical Engineering, 569, pp. 309-320. Cited 1 time.LinkDOI: 10.1007/978-981-13-8942-9_26",
        "link": "https://www.scopus.com/inward/record.uri?eid=2-s2.0-85073327308&doi=10.1007%2f978-981-13-8942-9_26&partnerID=40&md5=455a53a4b98eb3f483b8efe44b5f33bb"
    }
];

export const bookChapters2019_20 = [
    {
        "title": "Ramamurthy et al., \u201cInterpolation of the Histogramed MR Brain Images for Resolution Enhancement\u201d, Recent Developments in Engineering Research, 2020/BP/4963D, 18 May 2020, Google Scholar, Book Publisher International. https://www.bookpi.org/",
        "authors": "",
        "year_published": "",
        "publisher": "",
        "link": ""
    }
];

export const bookChapters2018_19 = [
    {
        "title": "Tirupal T., et al., \u201cMultimodal Medical Image Fusion based on Fuzzy sets with Orthogonal Teaching\u2013Learning-Based Optimization\u201d, In: Verma N., Ghosh A. (eds) Computational Intelligence: Theories, Applications and Future Directions \u2013 Volume II. Advances in Intelligent Systems and Computing, ISBN: 978-981-13-1134-5, vol 799, pp.487-499, October 2018, Springer, Singapore.Link",
        "authors": "",
        "year_published": "",
        "publisher": "",
        "link": "https://doi.org/10.1007/978-981-13-1135-2_37"
    },
    {
        "title": "S.Fowzia Sultana et al., \u201cEffective Approach To Enhance Teaching & Learning Process\u201d, Presented in Text Book Titled \u201cInnovative Teaching Practices For 4G Students\u201d ISBN: 978-93-88413-40-4, pp.222-224, April 2019, IOR International Press, Coimbatore, Tamilnadu.Link",
        "authors": "",
        "year_published": "",
        "publisher": "",
        "link": "https://www.iorpress.org/books/index.php/ior/catalog/view/1/4/333-1"
    },
    {
        "title": "V.Vijaya Kishore et al., \u201cRole of a Teacher: ICT and its effect on Pedagogy of Teaching and Learning\u201d, Presented in Text Book Titled \u201cInnovative Teaching Practices For 4G Students\u201d ISBN: 978-93-88413-40-4, pp.162-167, April 2019, IOR International Press, Coimbatore, Tamilnadu.Link",
        "authors": "",
        "year_published": "",
        "publisher": "",
        "link": "https://www.iorpress.org/books/index.php/ior/catalog/view/1/4/333-1"
    },
    {
        "title": "P.Bindu Swetha et al., \u201cEffective Approach To Enhance Teaching & Learning Process\u201d, Presented in Text Book Titled \u201cInnovative Teaching Practices For 4G Students\u201d ISBN: 978-93-88413-40-4, pp.222-224, April 2019, IOR International Press, Coimbatore, Tamilnadu.Link",
        "authors": "",
        "year_published": "",
        "publisher": "",
        "link": "https://www.iorpress.org/books/index.php/ior/catalog/view/1/4/333-1"
    }
];

