// This file is auto-generated by extract_research_resources.py

export const researchResources = [
    {
        "category": "Computer Science and Information Technology",
        "items": [
            {
                "title": "IEEE Transactions on Affective Computing (T-AFFC)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=5165369"
            },
            {
                "title": "IEEE Annals of the History of Computing (M-AHC)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=85"
            },
            {
                "title": "IEEE Transactions on Broadcasting, (T-BC)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=11"
            },
            {
                "title": "IEEE Cloud Computing",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=6509491"
            },
            {
                "title": "IEEE Transactions on Cloud Computing,",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=6245519"
            },
            {
                "title": "IEEE Transactions On Computational Intelligence and AI in Games (T-CIAIG)",
                "link": "https://ieeexplore.ieee.org/xpl/mostRecentIssue.jsp?punumber=4804728"
            },
            {
                "title": "IEEE Computational Intelligence Magazine (M-CI)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=10207"
            },
            {
                "title": "IEEE Transactions on Computational Social Systems (T-CSS)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=6570650"
            },
            {
                "title": "IEEE Computer Architecture Letters (L-CA)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=10208"
            },
            {
                "title": "IEEE Computer Graphics and Applications Magazine (M-CG&A)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=38"
            },
            {
                "title": "Computer Magazine (M-C)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=2"
            },
            {
                "title": "IEEE Transactions on Computers, (T-C)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=12"
            },
            {
                "title": "Computing in Science and Engineering (CiSE)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=5992"
            },
            {
                "title": "IEEE Transactions on Control of Network Systems, (T-CNS)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=6509490"
            },
            {
                "title": "IEEE Transactions on Control Systems Technology (T-CST)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=87"
            },
            {
                "title": "IEEE Transactions on Cybernetics, (T-CYB) Man, and Cybernetics, Part B: Cybernetics",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=6221036"
            },
            {
                "title": "IEEE Transaction on Dependable And Secure Computing(T-DSC)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=8858"
            },
            {
                "title": "IEEE Design and Test Magazine (M-D&T)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=6221038"
            },
            {
                "title": "IEEE Embedded Systems Letters (L-ES)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=4563995"
            },
            {
                "title": "IEEE Transactions. on Evolutionary Computation, (T-EVC)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=4235"
            },
            {
                "title": "IEEE Transactions. on Fuzzy Systems (T-FUZZ)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=91"
            },
            {
                "title": "IEEE Transactions.on Human-Machine Systems, (T-HMS)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=6221037"
            },
            {
                "title": "IEEE Transactions on Information Forensics and Security",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=10206"
            },
            {
                "title": "IEEE Transactions on Information Theory (T-IT)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=18"
            },
            {
                "title": "IEEE Intelligent Systems Magazine (M-IS)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=9670"
            },
            {
                "title": "IEEE Internet Computing Magazine (M-IC)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=4236"
            },
            {
                "title": "IEEE Internet of Things Journal (J-IOT)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=6488907"
            },
            {
                "title": "IT Professional Magazine (M-ITPRO)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=6294"
            },
            {
                "title": "IEEE Transactions on Knowledge and Data Engineering",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=69"
            },
            {
                "title": "IEEE Transactions on. Learning Technologies",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=4620076"
            },
            {
                "title": "IEEE Micro Magazine (M-MICRO)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=40"
            },
            {
                "title": "IEEE Transactions on Mobile Computing,",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=7755"
            },
            {
                "title": "IEEE Multi Media Magazine (M-MULTI)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=93"
            },
            {
                "title": "IEEE Transactions on Multimedia,",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=6046"
            },
            {
                "title": "IEEE Transactions on Network and Service Management,",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=4275028"
            },
            {
                "title": "IEEE Transactions on Network Science and Engineering,",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=6488902"
            },
            {
                "title": "IEEE Network: The Magazine of Global Internetworking (M-NET)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=65"
            },
            {
                "title": "IEEE/ACM Transactions on Networking, (T-NET)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=90"
            },
            {
                "title": "IEEE Transactions on Neural Networks and Learning Systems (T-NNLS)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=5962385"
            },
            {
                "title": "IEEE Transactions on Parallel and Distributed Systems",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=71"
            },
            {
                "title": "IEEE Transactions on Pattern Analysis and Machine Intelligence",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=34"
            },
            {
                "title": "IEEE Persive Computing Magazine",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=7756"
            },
            {
                "title": "IEEE Transactions on Services Computing, (T-SC)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=4629386"
            },
            {
                "title": "IEEE Transactions on Software Engineering (T-SE)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=32"
            },
            {
                "title": "IEEE Software Magazine (M-SOFT)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=52"
            },
            {
                "title": "IEEE Systems Journal (J-SYS)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=4267003"
            },
            {
                "title": "IEEE Transactions on Systems, Man, and Cybernetics: Systems (T-SMC)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=6221037"
            },
            {
                "title": "IEEE Technology and Society Magazine (M-T&S)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=44"
            },
            {
                "title": "IEEE Transactions on Visualization and Computer Graphics (T-VCG)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=2945"
            }
        ]
    },
    {
        "category": "Electronics and Communication Engineering",
        "items": [
            {
                "title": "IEEE Antennas and Propagation Magazine (M-AP)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=74"
            },
            {
                "title": "IEEE Transactions on (Antennas and Propagation, (T-AP)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=8"
            },
            {
                "title": "IEEE Antennas and Wireless Propagation Letters (L-AWP)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=7727"
            },
            {
                "title": "IEEE/ACM Transactions. on Audio, Speech, and Language Processing, (T-ASL)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=10376"
            },
            {
                "title": "IEEE Transactions on Automatic Control, (T-AC)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=9"
            },
            {
                "title": "IEEE/CAA Journal of Automatic Sinica (J-AS)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=6570654"
            },
            {
                "title": "China Communications (M-CHINA)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=6245522"
            },
            {
                "title": "IEEE Circuits and Systems (M-CAS)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=7384"
            },
            {
                "title": "IEEE Transactions On Circuits and Systems for Video Technology (T-CSVT)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=76"
            },
            {
                "title": "IEEE Transactions. on (T-CAS1)Circuits and Systems Part I: Regular Papers",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=8919"
            },
            {
                "title": "IEEE Transactions on Circuits and Systems Part II: Express Briefs (T-CAS2)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=8920"
            },
            {
                "title": "IEEE Communications Letters (L-COMM)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=4234"
            },
            {
                "title": "IEEE Communications Magazine (M-COMM)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=35"
            },
            {
                "title": "IEEE Transactions. on Communications (T-COMM)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=26"
            },
            {
                "title": "IEEE Communications Surveys & Tutorials (COMST)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=9739"
            },
            {
                "title": "IEEE/ACM Transactions. on Computational Biology and Bioinformatics (T-CBB)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=8857"
            },
            {
                "title": "IEEE Transactions. on Computer-Aided Design of Integrated Circuits and Systems, I (T-CAD)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=43"
            },
            {
                "title": "IEEE Consumer Electronics Magazine (M-CE)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=5962380"
            },
            {
                "title": "IEEE Transactions on Consumer Electronics (T-CE)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=30"
            },
            {
                "title": "IEEE Control Systems Magazine (M-CS)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=37"
            },
            {
                "title": "IEEE Transactions. on Device and Materials Reliability (T-DMR)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=7298"
            },
            {
                "title": "Journal of Display Technology,",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=9425"
            },
            {
                "title": "IEEE Electromagnetic Compatibility Magazine(M-EMC)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=5962381"
            },
            {
                "title": "IEEE Transactions on Electromagnetic Compatibility, (T-EMC)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=15"
            },
            {
                "title": "IEEE Electron Device Letters (L-ED)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=55"
            },
            {
                "title": "IEEE Transactions. on Electron Devices, (T-ED)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=16"
            },
            {
                "title": "IEEE Journal of Emerging And Selected Topics in Circuits And Systems(JETCAS)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=5503868"
            },
            {
                "title": "IEEE Journal of Emerging and Selected Topics in Power Electronics, (J-ESTPE)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=6245517"
            },
            {
                "title": "IEEE Transactions. on Energy Conversion, (T-EC)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=60"
            },
            {
                "title": "IEEE Transactions. on Image Processing, (T-IP)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=83"
            },
            {
                "title": "IEEE Industrial Electronics (M-IE)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=4154573"
            },
            {
                "title": "IEEE Transactions. on Industrial Electronics, (T-IE)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=41"
            },
            {
                "title": "IEEE Transactions. on Industrial Informatics (T-IINF)",
                "link": "http://www.ieee-ies.org/pubs/transactions-on-industrial-informatics"
            },
            {
                "title": "IEEE Industry Applications Magazine (M-IA)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=2943"
            },
            {
                "title": "IEEE Transactions. on Industry Applications (T-IA)",
                "link": "https://ieeexplore.ieee.org/document/4503405"
            },
            {
                "title": "IEEE Instrumentation and Measurement Magazine",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=5289"
            },
            {
                "title": "IEEE Transactions. on Instrumentation and Measurement on Includes Instrumentation and Measurement",
                "link": "https://ieeexplore.ieee.org/document/1360095"
            },
            {
                "title": "IEEE Transactions. On Instrumentation and Measurement",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=19"
            },
            {
                "title": "Journal of Light wave Technology, (J-LT)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=50"
            },
            {
                "title": "IEEE Magnetics Letters (L-MAG)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=5165412"
            },
            {
                "title": "IEEE Transactions. on Magnetics (T-MAG)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=20"
            },
            {
                "title": "IEEE Microwave and Wireless Components Letters",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=7260"
            },
            {
                "title": "IEEE Microwave Magazine (M-MW)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=6668"
            },
            {
                "title": "IEEE Transactions. on Microwave Theory and Techniques",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=22"
            },
            {
                "title": "IEEE Transactions. on Nuclear Science, (T-NS)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=23"
            },
            {
                "title": "IEEE/OSA Journal of (J-OCN) Optical Communications and Networking",
                "link": "https://ieeexplore.ieee.org/document/5483683"
            },
            {
                "title": "IEEE Photonics Technology Letters (L-PT)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=68"
            },
            {
                "title": "IEEE Journal on Photo voltaic (J-PHOTOV)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=5503869"
            },
            {
                "title": "IEEE Transactions on Plasma Science (T-PS)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=27"
            },
            {
                "title": "IEEE Transactions on Professional Communication (T-PC)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=47"
            },
            {
                "title": "IEEE Journal of (J-QE) Quantum Electronics",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=3"
            },
            {
                "title": "IEEE Transactions on Reliability (T-R)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=24"
            },
            {
                "title": "IEEE Journal of Selected Areas in Communications (J-SAC)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=49"
            },
            {
                "title": "IEEE Journal of (J-STQE) Selected Topics in Quantum Electronics",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=2944"
            },
            {
                "title": "IEEE Journal of (J-STSP) Selected Topics in Signal Processing",
                "link": "http://ieeexplore.ieee.org/document/8688694"
            },
            {
                "title": "IEEE Journal of Sensors (J-SEN)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=7361"
            },
            {
                "title": "IEEE Signal Processing Letters (L-SP)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=97"
            },
            {
                "title": "IEEE Signal Processing Magazine (M-SP)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=79"
            },
            {
                "title": "IEEE Transactions on Signal Processing (T-SP)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=78"
            },
            {
                "title": "IEEE Transactions on Terahertz Science and Technology",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=5503871"
            },
            {
                "title": "IEEE Transactions on Ultra Sonics, Ferroelectrics, and Frequency Control (T-UFFC)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=58"
            },
            {
                "title": "IEEE Wireless Communications Letters (L-WC)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=5962382"
            },
            {
                "title": "IEEE Wireless Communications Magazine (M-WC)",
                "link": "https://ieeexplore.ieee.org/document/5714016"
            },
            {
                "title": "IEEE Transactions on Wireless Communications (T-WC)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=7693"
            }
        ]
    },
    {
        "category": "Electrical and Electronics Engineering",
        "items": [
            {
                "title": "IEEE Transactions On Applied Superconductivity, (T-ASC)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=77"
            },
            {
                "title": "IEEE Transactions on Dielectrics and Electrical Insulation, (T-DEI)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=94"
            },
            {
                "title": "IEEE Electrical Insulation Magazine (M-EI)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=57"
            },
            {
                "title": "IEEE Electrification Magazine (E-M) (late 2013)",
                "link": "https://www.ieee-pes.org/publications/electrification-magazine"
            },
            {
                "title": "IEEE Transactions on Intelligent transportation Systems Magazine",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=5117645"
            },
            {
                "title": "IEEE Transactions on Power Delivery (T-PWRD)",
                "link": "https://cmte.ieee.org/tpwrd/pwrd-resource-site-papers-received-favorable-reviews/"
            },
            {
                "title": "IEEE Power Electronics Magazine (M-PEL)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=6570649"
            },
            {
                "title": "IEEE Transactions on Power Electronics (T-PEL)",
                "link": "https://www.ieee-pels.org/publications/ieee-power-electronics-letters"
            },
            {
                "title": "IEEE Power & Energy Magazine (M-P&E)",
                "link": "https://magazine.ieee-pes.org/"
            },
            {
                "title": "IEEE Transactions. on Power Systems, (T-PWRS)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=59"
            },
            {
                "title": "IEEE Transactions on Smart Grid (T-SG)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=5165411"
            },
            {
                "title": "IEEE Solid-State Circuits Magazine (M-SSC)",
                "link": "https://sscs.ieee.org/publications/ieee-solid-state-circuits-magazine"
            },
            {
                "title": "IEEE Journal of (J-SSC) Solid-State Circuits",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=4"
            },
            {
                "title": "IEEE Transactions on Sustainable Energy (T-STE)",
                "link": "http://ieeexplore.ieee.org/document/8320237"
            },
            {
                "title": "IEEE Vehicular Technology Magazine (M-VT)",
                "link": "http://www.ieeevtc.org/vtmagazine/"
            },
            {
                "title": "IEEE Transactions on Vehicular Technology (T-VT)",
                "link": "https://site.ieee.org/connected-vehicles/publications/ieee-transactions-on-vehicular-technology/"
            },
            {
                "title": "IEEE Transactions on Vehicular Technology (T-VLSI)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=25"
            }
        ]
    },
    {
        "category": "Civil Engineering",
        "items": [
            {
                "title": "IEEE Geosciences and Remote Sensing Letters (L-GRS)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=8859"
            },
            {
                "title": "IEEE Geosciences and Remote Sensing Magazine (M-GRS)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=6245518"
            },
            {
                "title": "IEEE Transactions. on Geosciences and Remote Sensing,",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=36"
            },
            {
                "title": "IEEE Journal of Oceanic Engineering (J-OE)",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=48"
            },
            {
                "title": "IEEE Journal of (J-STARS) Selected Topics in Applied Earth Observations and Remote Sensing,",
                "link": "https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=4609443"
            }
        ]
    }
];
